// Rechecks retained evidence and seeded decisions; does not rerun private input or a provider.
const assert=require('assert'),fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process');
const base=path.join(__dirname,'replay'),read=f=>JSON.parse(fs.readFileSync(path.join(base,f),'utf8'));
let executed=0;const check=(name,fn)=>{fn();executed++;return name;};const checks=[];
checks.push(check('Real experiment distinguishes failed traversal from observed root access',()=>{
 const rows=fs.readdirSync(path.join(base,'pastor')).filter(n=>n.startsWith('experiment-')&&n.endsWith('.json')&&n!=='experiment-collection.json').map(n=>read('pastor/'+n));
 assert.strictEqual(rows.length,3);assert(rows.every(r=>r.productionAccepted===false));
 const failed=rows.find(r=>{try{return JSON.parse(r.stdout).error_class==='OSError';}catch{return false;}});assert(failed&&failed.outcome==='failed'&&failed.exitCode!==0);assert(failed.sandboxProbe.passed);
 const observed=rows.find(r=>r.outcome==='observed');assert(observed&&observed.exitCode===0&&observed.sandboxProbe.passed);const raw=JSON.parse(observed.stdout);assert(raw.archive_opened&&raw.root_folder_read&&raw.stable_input);assert.strictEqual(raw.private_content_emitted,false);assert(raw.scope.includes('not extraction qualification'));
}));
checks.push(check('Every real attempt has a collected outcome, including failure',()=>{const j=read('pastor/experiment-collection.json');assert.strictEqual(Object.keys(j.batches).length,3);assert(Object.values(j.batches).every(b=>b.collection==='reported'));assert(j.discoveries.some(d=>d.id==='parser-structure-oserror'));assert(j.discoveries.some(d=>d.id==='parser-root-access-observed'));}));
checks.push(check('Real privacy scanner checked a real baseline canary before export',()=>{const p=read('pastor/all-privacy-proof.json');assert(p.success);const a=JSON.parse(p.actual);assert(a.canary_detected&&a.secret_forms_checked>0&&a.files_scanned>=11);assert.strictEqual(a.issues_with_private_values,0);}));
checks.push(check('Actual observations invalidate only the supplied affected consumer',()=>{const p=read('pastor/discovery-propagation.json');assert.strictEqual(p.productionConsumer.status,'blocked');assert(p.productionConsumer.discoveries.length>=3);assert.strictEqual(p.unrelated.status,'planning');assert.strictEqual(p.unrelated.discoveries.length,0);}));
checks.push(check('Mixed-tier frontier keeps future work thin and accounts for linked volume',()=>{const f=read('pastor/replay-frontier.json');assert(f.tickets.some(t=>t.tier==='contracted'));assert(f.tickets.some(t=>t.tier==='build-ready'&&t.stale));for(const n of [5902,5903]){const r=f.tickets.find(t=>t.issue===n);assert.strictEqual(r.tier,'thin');assert.strictEqual(r.stale,false);}assert(f.tickets.every(t=>t.volume.bodyCharacters<=30000));assert.deepStrictEqual(f.volume.errors,[]);assert(f.volume.linkedMaintainedCharacters>0&&f.volume.historicalCharacters>0);assert(f.volume.maintainedTotalCharacters>=f.volume.bodyCharacters);const v=read('pastor/replay-volume.json');assert(v.counts.reused>0&&v.counts.deferred>0&&v.counts.new>0);}));
checks.push(check('Current Specflow tickets satisfy body limits without claiming legacy Pastor cleanup',()=>{const sizes=read('ticket-sizes.json');assert.strictEqual(sizes.length,6);assert(sizes.every(r=>r.underMaximum));const legacy=read('pastor/existing-volume.json');assert(legacy.existingIssues.some(r=>r.overMaximum));assert(legacy.aggregate.unmeasuredOrBrokenReferenceCount>0);}));
checks.push(check('Live peer attempt provenance, protocol failure and accepted correction are distinct',()=>{const r=read('native/result.json'),first=read('native/round-1.json'),second=read('native/round-2.json');assert.strictEqual(r.goalStatus,'complete');assert.strictEqual(first.protocolValidated,false);assert.strictEqual(first.structured_output.outcome,'changes_required');assert(first.structured_output.findings.length>=5);assert.strictEqual(second.protocolValidated,true);assert.strictEqual(second.structured_output.outcome,'accepted');assert.strictEqual(second.structured_output.findings.length,0);assert.strictEqual(second.invocation.exe,'claude');assert(second.invocation.args.includes('-p'));const rounds=r.scopedJournal.reviews.contracted;assert.strictEqual(rounds.length,2);assert.strictEqual(rounds[1].identity.mode,'live');assert.strictEqual(rounds[1].identity.model,'claude-opus-5-5');assert.strictEqual(rounds[1].outcome,'passed');assert(r.scopedJournal.transitions.some(t=>t.tier==='contracted'));assert(r.gateExecutions.some(g=>g.executed===5&&g.failed===5));assert(r.gateExecutions.some(g=>g.executed===5&&g.failed===0&&g.skipped===0));}));
checks.push(check('Re-executed seeded decisions fail before correction and pass after',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'density-proof-'));try{fs.copyFileSync(path.join(base,'native/check.cjs'),path.join(dir,'check.cjs'));for(const [round,expected]of [[1,1],[2,0]]){fs.copyFileSync(path.join(base,`native/decisions-${round}.json`),path.join(dir,'decisions.json'));const r=cp.spawnSync(process.execPath,['check.cjs'],{cwd:dir,encoding:'utf8'});assert.strictEqual(r.status,expected);const result=JSON.parse(r.stdout);assert.strictEqual(result.executed,5);assert.strictEqual(result.skipped,0);assert.strictEqual(result.failed,round===1?5:0);}}finally{fs.rmSync(dir,{recursive:true,force:true});}}));
console.log(JSON.stringify({kind:'retained-replay-verification',executed,skipped:0,failed:0,checks,limits:'Rechecks retained raw results and re-executes seeded decision assertions. Does not rerun the private parser, a live provider, or production behaviour.'},null,2));
