const fs = require('fs'), os = require('os'), path = require('path');
const routing = require('../../scripts/typesafe-routing.cjs');
function manifest(projects = ['https://github.com/test/one']) { return { version: 1, id: 'test-study', projects, jevModel: 'jev-1.13.0', model: 'claude-opus-5-5', efforts: ['medium', 'high'], baseline: { 'spec-build': 'medium', 'feature-build': 'medium' }, budget: { typesafe: 200, native: 400 }, maxPerRun: { typesafe: 10, native: 4 }, timeoutMs: 100, nativeTimeoutMs: 15000, maxOutputBytes: 1048576, reviewer: { model: 'gpt-5.5', effort: 'medium' }, taskClass: 'bounded-file-change', maxRepairRounds: 0, seed: 160, resamples: 1000, primaryMetric: 'elapsedMs', calibrationFamilies: [], heldoutFamilies: [] }; }
function setup(m = manifest()) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'routing-study-')); const study = routing.init(dir, m); return { dir, study, close: () => fs.rmSync(dir, { recursive: true, force: true }) }; }
function task(i = 1, changes = {}) { return { repository: 'https://github.com/test/one', taskFamilyId: 'task-' + i, runId: 'run-' + i, loop: 'feature-build', stage: 'implementation', attempt: 0, snapshotHash: 'snapshot-' + i, goal: 'Count distinct subscriptions accurately', acceptance: 'AC-1 count unique subscription identities, preserving unknowns.', context: 'Records have stable subscription IDs.', recentEvidence: [], evidenceRefs: ['task.json'], configured: { model: 'claude-opus-5-5', effort: 'medium' }, requested: { model: 'claude-opus-5-5', effort: 'medium' }, ...changes }; }
function answers(changes = {}) { return Object.fromEntries(Object.entries(routing.questions).map(([key, q]) => { const choice = changes[key] || Object.keys(q.criteria)[0]; return [key, { type: 'choice', choice, confidence: 1, probabilities: Object.fromEntries(Object.keys(q.criteria).map(c => [c, c === choice ? 1 : 0])) }]; })); }
const fetchImpl = async () => new Response(JSON.stringify({ model: 'jev-1.13.0', answers: answers(), usage: { input_tokens: 12, output_tokens: 4 } }));
function caseInput() { return { repository: 'https://github.com/test/one', taskFamilyId: 'sum', loop: 'feature-build', stage: 'sum-values', goal: 'Calculate the displayed total accurately', acceptance: 'AC-1 add two signed numeric inputs; preserve zero.', independentUnit: true, files: { 'sum.cjs': 'exports.sum = () => 0;\n', 'verify.cjs': `const {sum}=require('./sum.cjs'); const checks=[{id:'AC-1',status:sum(7,-3)===4&&sum(0,0)===0?'passed':'failed'}]; console.log(JSON.stringify({checks})); process.exitCode=checks.some(c=>c.status!=='passed')?1:0;` }, editable: ['sum.cjs'], oracle: { path: 'verify.cjs', requiredChecks: ['AC-1'] } }; }
function nativeDouble(command, args, options) {
  if (command === 'claude') { const effort = args[args.indexOf('--effort') + 1]; return { status: 0, stdout: [ { type: 'system', subtype: 'init', model: 'claude-opus-5-5', effort }, { type: 'result', subtype: 'success', is_error: false, structured_output: { files: [{ path: 'sum.cjs', content: 'exports.sum = (a,b) => a+b;\n' }] } } ].map(JSON.stringify).join('\n'), stderr: '' }; }
  if (command === 'codex') { const content = fs.readFileSync(path.join(options.cwd, 'input.json'), 'utf8'); return { status: 0, stdout: [ { type: 'item.completed', item: { id: 'read-1', type: 'command_execution', command: 'cat input.json', status: 'completed', exit_code: 0, aggregated_output: content } }, { type: 'item.completed', item: { type: 'agent_message', text: JSON.stringify({ outcome: 'accepted', materialViolation: false, findings: [] }) } } ].map(JSON.stringify).join('\n'), stderr: '' }; }
  throw Error('Unexpected native command');
}
module.exports = { manifest, setup, task, answers, fetchImpl, caseInput, nativeDouble };
